services:
  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.17.1
  #   container_name: elasticsearch
  #   hostname: elasticsearch
  #   environment:
  #     - discovery.type=single-node
  #     - xpack.security.enabled=false
  #   healthcheck:
  #     test: [ "CMD", "curl", "-f", "http://localhost:9200/_cluster/health" ]
  #     interval: 10s
  #     retries: 5
  #     timeout: 5s
  #   ports:
  #     - 9200:9200
  #   volumes:
  #     - es_data:/usr/share/elasticsearch/data

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:8.17.1
  #   container_name: kibana
  #   depends_on:
  #     elasticsearch:
  #       condition: service_healthy
  #   ports:
  #     - "5601:5601"

  fluentd:
    build: ./fluentd
    container_name: fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"

# volumes:
#   es_data:
#     driver: local